service: s3-directory-list

plugins:
  - serverless-external-s3-event
  - serverless-webpack

custom:
  bucketName: ${file(custom.yml):bucketName}
  darkTheme: ${file(custom.yml):darkTheme, 'false'}

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 256

  stage: dev
  region: eu-west-1
  profile: serverless


  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:ListBucket"
     Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
   - Effect: "Allow"
     Action:
       - "s3:PutObject"
     Resource:
       Fn::Join:
         - ""
         - - "arn:aws:s3:::"
           - "Ref" : "ServerlessDeploymentBucket"
           - "/*"
   - Effect: "Allow"
     Action:
       - "s3:ListBucket"
     Resource: "arn:aws:s3:::${self:custom.bucketName}"
   - Effect: "Allow"
     Action:
       - "s3:GetObject"
       - "s3:PutObject"
     Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

   - Effect: "Allow"
     Action:
      - "s3:PutBucketNotification"
     Resource:
      Fn::Join:
        - ""
        - - "arn:aws:s3:::${self:custom.bucketName}"

functions:
  generateListing:
    handler: src/handler.generateListing
    environment:
      darkTheme: ${self:custom.darkTheme}
    events:
      - existingS3:
          bucket: ${self:custom.bucketName}
          events:
            - s3:ObjectCreated:*
            - s3:ObjectRemoved:*
      # - s3:
      #     bucket: ${self:custom.bucketName}
      #     events:
      #       - s3:ObjectCreated:*
      #       - s3:ObjectRemoved:*
